MrCMS.Web/Apps/Amazon/Entities/Logs/AmazonLog.cs
using System;
using MrCMS.Entities;
using MrCMS.Entities.People;
using MrCMS.Web.Apps.Amazon.Entities.Listings;
using MrCMS.Web.Apps.Amazon.Entities.Orders;
using MrCMS.Web.Apps.Amazon.Models;

namespace MrCMS.Web.Apps.Amazon.Entities.Logs
{
    public class AmazonLog : SiteEntity
    {
        public virtual AmazonLogType LogType { get; set; }
        public virtual AmazonLogStatus LogStatus { get; set; }

        public virtual AmazonApiSection? ApiSection { get; set; }
        public virtual string ApiOperation { get; set; }

        public virtual AmazonOrder AmazonOrder { get; set; }
        public virtual AmazonListing AmazonListing { get; set; }
        public virtual AmazonListingGroup AmazonListingGroup { get; set; }

        public virtual string ErrorCode { get; set; }
        public virtual string ErrorType { get; set; }
        public virtual string Message { get; set; }
        public virtual string Detail { get; set; }

        public virtual User User { get; set; }
    }
}

MrCMS.Web/Apps/Amazon/Areas/Admin/Controllers/LogsController.cs
using MrCMS.Settings;
using MrCMS.Web.Apps.Amazon.Entities.Logs;
using MrCMS.Web.Apps.Amazon.Models;
using MrCMS.Web.Apps.Amazon.Services.Logs;
using MrCMS.Website.Controllers;
using System.Web.Mvc;

namespace MrCMS.Web.Apps.Amazon.Areas.Admin.Controllers
{
    public class LogsController : MrCMSAppAdminController<AmazonApp>
    {
        private readonly IAmazonLogService _amazonLogService;
        private readonly SiteSettings _siteSettings;

        public LogsController(IAmazonLogService amazonLogService, SiteSettings siteSettings)
        {
            _amazonLogService = amazonLogService;
            _siteSettings = siteSettings;
        }

        [HttpGet]
        public ViewResult Index(AmazonLogType? type, AmazonLogStatus? status, int page = 1)
        {
            var model = _amazonLogService.GetEntriesPaged(page, type, status, _siteSettings.DefaultPageSize);
            return View(model);
        }

        [HttpPost]
        [ActionName("Index")]
        public RedirectToRouteResult Index_POST(AmazonLogType? type, AmazonLogStatus? status)
        {
            return RedirectToAction("Index", new { type,status });
        }

        public ViewResult Details(AmazonLog entry)
        {
            return View(entry);
        }

        [HttpGet]
        public ActionResult DeleteAllLogs()
        {
            return PartialView();
        }

        [HttpPost]
        [ActionName("DeleteAllLogs")]
        public ActionResult DeleteAllLogs_POST()
        {
            _amazonLogService.DeleteAllLogs();
            _amazonLogService.Add(AmazonLogType.Logs, AmazonLogStatus.Delete, null, null, null, null, null, null, null, null);
            return RedirectToAction("Index");
        }
    }
}

MrCMS.Web/Apps/Amazon/Areas/Admin/Views/Logs/DeleteAllLogs.cshtml
@{ Layout = "~/Areas/Admin/Views/Shared/_LayoutPopup.cshtml";}
@using (Html.BeginForm("DeleteAllLogs", "Logs", FormMethod.Post, new { style = "display:inline;" }))
{
    <fieldset>
        <legend>Delete all logs?
                <span class="btn-group  display-inline  pull-right">
                    <input type="submit" class="btn btn-danger" value="Delete Logs" />
                </span>
        </legend>
        <p>Deleting this cannot be undone.</p>
    </fieldset>
}

MrCMS.Web/Apps/Amazon/Areas/Admin/Views/Logs/Details.cshtml
@using System.Web.Mvc.Html
@using MrCMS.Web.Apps.Ecommerce.Helpers
@model MrCMS.Web.Apps.Amazon.Entities.Logs.AmazonLog
@{
    ViewBag.Title = "View Amazon Log #" + Model.Id;
}

<fieldset>
    <legend>
        Amazon Log #@Model.Id
        <span class="btn-group  display-inline  pull-right">
            @Html.ActionLink("Back to Logs", "Index", "Logs", null, new { @class = "btn btn-primary" })
        </span>
    </legend>
</fieldset>

<table class="table table-striped table-condensed">
    <tbody>
        <tr>
            <td class="col-lg-4">
                Type
            </td>
            <td class="col-lg-8">
                @Model.LogType.GetDescription()
            </td>
        </tr>
        <tr>
            <td>
                Status
            </td>
            <td>
                @Model.LogStatus.GetDescription()
            </td>
        </tr>
        <tr>
            <td>
                Created on
            </td>
            <td>
                @Model.CreatedOn
            </td>
        </tr>
        @if (Model.User != null)
        {
            <tr>
                <td>
                    User
                </td>
                <td>
                    @Model.User.Name
                </td>
            </tr>
        }
        @if (Model.ApiSection.HasValue)
        {
            <tr>
                <td>
                    Api Section
                </td>
                <td>
                    @Model.ApiSection.Value
                </td>
            </tr>
        }
        @if (!String.IsNullOrWhiteSpace(Model.ApiOperation))
        {
            <tr>
                <td>
                    Api Operation
                </td>
                <td>
                    @Model.ApiOperation
                </td>
            </tr>
        }
        @if (Model.AmazonListingGroup != null)
        {
            <tr>
                <td>
                    Amazon Listing Group
                </td>
                <td>
                    @Html.ActionLink("Details", "Edit", "ListingGroup", new { id = Model.AmazonListingGroup.Id }, null)
                </td>
            </tr>
        }
        @if (Model.AmazonListing != null)
        {
            <tr>
                <td>
                    Amazon Listing
                </td>
                <td>
                    @Html.ActionLink("Details", "Details", "Listing", new { id = Model.AmazonListing.Id }, null)
                </td>
            </tr>
        }
        @if (Model.AmazonOrder != null)
        {
            <tr>
                <td>
                    Amazon Order
                </td>
                <td>
                    @Html.ActionLink("Details", "Details", "Orders", new { id = Model.AmazonOrder.Id }, null)
                </td>
            </tr>
        }
        @if (!String.IsNullOrWhiteSpace(Model.ErrorCode))
        {
            <tr>
                <td>
                    Error Code
                </td>
                <td>
                    @Model.ErrorCode
                </td>
            </tr>
        }
        @if (!String.IsNullOrWhiteSpace(Model.ErrorType))
        {
            <tr>
                <td>
                    Error Type
                </td>
                <td>
                    @Model.ErrorType
                </td>
            </tr>
        }
        @if (!String.IsNullOrWhiteSpace(Model.Message))
        {
            <tr>
                <td>
                    Message
                </td>
                <td>
                    @Model.Message
                </td>
            </tr>
        }
        @if (!String.IsNullOrWhiteSpace(Model.Detail))
        {
            <tr>
                <td>
                    Detail
                </td>
                <td>
                    @Model.Detail
                </td>
            </tr>
        }
    </tbody>
</table>

MrCMS.Web/Apps/Amazon/Areas/Admin/Views/Logs/Index.cshtml
@using System.Web.Mvc
@using System.Web.Mvc.Html
@using MrCMS.Helpers
@using MrCMS.Web.Apps.Amazon.Helpers
@using MrCMS.Web.Apps.Amazon.Models
@using MrCMS.Web.Apps.Ecommerce.Helpers
@model MrCMS.Paging.IPagedList<MrCMS.Web.Apps.Amazon.Entities.Logs.AmazonLog>
@{
    ViewBag.Title = "Amazon Logs";
}
@using (Html.BeginForm("Index", "Logs", new {id = ""}, FormMethod.Get, new {id = "edit-settings"}))
{
    <fieldset>
        <legend>Amazon Logs 
            <span class="btn-group  display-inline  pull-right">
                @Html.ActionLink("Delete All Logs", "DeleteAllLogs", "Logs", new {id = ""}, new {@class = "btn btn-danger", data_toggle = "fb-modal"})
                <button class="btn btn-primary" type="submit">Filter Logs</button>
            </span>
        </legend>
    </fieldset>

    <div class="form-group">
        @Html.Label("type", "Filter Logs")
        @Html.DropDownList("type", Enum.GetValues(typeof(AmazonLogType)).OfType<AmazonLogType>().BuildSelectItemList(type => type.GetDescription(), type => type.ToString(), type => type.ToString() == Request["type"], "All"), new{@class="form-control"})
    </div>
}


@if (Model.Count == 0)
{
    @:No results.
}
else
{
    <table class="table table-striped table-condensed" style="overflow: scroll">
        <thead>
            <tr>
                <th>Date
                </th>
                 <th>User
                </th>
                 <th>Type
                </th>
                <th>Status
                </th>
                <th>Message
                </th>
                <th>Actions
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var entry in Model)
            {
                <tr>
                    <td>
                        @entry.CreatedOn.ToString("dd/MM/yyyy HH:mm:ss")
                    </td>
                     <td>
                        @(entry.User!=null?entry.User.Name:"System")
                    </td>
                    <td>
                        @entry.LogType.GetDescription()
                    </td>
                    <td>
                        @entry.LogStatus.GetDescription()
                    </td>
                    <td>
                        @entry.Message.ToShortString(40)
                    </td>
               
                    <td>
                        @Html.ActionLink("Details", "Details", new {id = entry.Id})
                    </td>
                </tr>
            }
        </tbody>
    </table>
}
@Html.Pager(Model, "Index", i => new { page = i })