MrCMS.Web/Apps/Ecommerce/Areas/Admin/Controllers/PayPalExpressCheckoutSettingsController.cs
using System.Web.Mvc;
using MrCMS.Settings;
using MrCMS.Web.Apps.Ecommerce.ACL;
using MrCMS.Web.Apps.Ecommerce.Areas.Admin.ModelBinders;
using MrCMS.Web.Apps.Ecommerce.Payment.PayPalExpress;
using MrCMS.Website;
using MrCMS.Website.Binders;
using MrCMS.Website.Controllers;

namespace MrCMS.Web.Apps.Ecommerce.Areas.Admin.Controllers
{
    public class PayPalExpressCheckoutSettingsController : MrCMSAppAdminController<EcommerceApp>
    {
        private readonly IConfigurationProvider _configurationProvider;

        public PayPalExpressCheckoutSettingsController(IConfigurationProvider configurationProvider)
        {
            _configurationProvider = configurationProvider;
        }

        [HttpGet]
        [MrCMSACLRule(typeof(PayPalExpressCheckoutSettingsACL), PayPalExpressCheckoutSettingsACL.View)]
        public ActionResult Index()
        {
            return View(_configurationProvider.GetSiteSettings<PayPalExpressCheckoutSettings>());
        }

        [HttpPost]
        [MrCMSACLRule(typeof(PayPalExpressCheckoutSettingsACL), PayPalExpressCheckoutSettingsACL.View)]
        public RedirectToRouteResult Save(
            [IoCModelBinder(typeof (PayPalExpressCheckoutSettingsModelBinder))] PayPalExpressCheckoutSettings settings)
        {
            _configurationProvider.SaveSettings(settings);
            return RedirectToAction("Index");
        }
    }
}

MrCMS.Web/Apps/Ecommerce/Areas/Admin/Views/PayPalExpressCheckoutSettings/Index.cshtml
@using MrCMS.Helpers
@model MrCMS.Web.Apps.Ecommerce.Payment.PayPalExpress.PayPalExpressCheckoutSettings
@{
    ViewBag.Title = "PayPal Express Checkout Settings";
}
@using (Html.BeginForm("Save", "PayPalExpressCheckoutSettings", FormMethod.Post))
{
    <fieldset>
        <legend>
            PayPal Express Checkout Settings

            <span class="btn-group display-inline pull-right">
                <input type="submit" class="btn btn-primary" value="Save" />
            </span>
        </legend>
        <div class="form-group">
            @Html.InlineCheckboxFor(settings => settings.Enabled, null, null)
        </div>
        <div class="form-group">
            @Html.InlineCheckboxFor(settings => settings.IsLive, null, null)
        </div>
        <div class="form-group">
            @Html.LabelFor(settings => settings.LocaleCode)
            @Html.TextBoxFor(settings => settings.LocaleCode, new{@class="form-control"})
        </div>
        <div class="form-group">
            @Html.LabelFor(settings => settings.LogoImageURL)<br />
            @Html.TextBoxFor(settings => settings.LogoImageURL, new { @class = "form-control" })
        </div>
        <div class="form-group">
            @Html.LabelFor(settings => settings.CartBorderColor)
            @Html.TextBoxFor(settings => settings.CartBorderColor, new { @class = "form-control" })
        </div>
        <div class="form-group">
            @Html.InlineCheckboxFor(settings => settings.RequireConfirmedShippingAddress, null, null)
        </div>
        <div class="form-group">
            @Html.InlineCheckboxFor(settings => settings.HaveBusinessAccount, null, null)
        </div>
        <div class="form-group">
            @Html.LabelFor(settings => settings.UserName)
            @Html.TextBoxFor(settings => settings.UserName, new { @class = "form-control" })
        </div>
        <div class="form-group">
            @Html.LabelFor(settings => settings.Password)
            @Html.TextBoxFor(settings => settings.Password, new { @class = "form-control" })
        </div>
        <div class="form-group">
            @Html.LabelFor(settings => settings.Signature)
            @Html.TextBoxFor(settings => settings.Signature, new { @class = "form-control" })
        </div>
        <div class="form-group">
            @Html.LabelFor(settings => settings.SubjectEmailAddress)
            @Html.TextBoxFor(settings => settings.SubjectEmailAddress, new { @class = "form-control" })
        </div>
        <div class="form-group">
            @Html.LabelFor(settings => settings.Currency)
            @Html.DropDownListFor(settings => settings.Currency, Model.CurrencyOptions, new { @class = "form-control" })
        </div>
        <div class="form-group">
            @Html.LabelFor(settings => settings.PaymentAction)
            @Html.DropDownListFor(settings => settings.PaymentAction, Model.PaymentActionOptions, new { @class = "form-control" })
        </div>
    </fieldset>
}