MrCMS.Web/Apps/Ecommerce/Entities/Products/Wishlist.cs
using System;
using System.Collections.Generic;
using MrCMS.Entities;

namespace MrCMS.Web.Apps.Ecommerce.Entities.Products
{
    public class Wishlist : SiteEntity
    {
        public Wishlist()
        {
            WishlistItems = new List<WishlistItem>();
        }

        public virtual string Name { get; set; }
        public virtual Guid UserGuid { get; set; }
        public virtual IList<WishlistItem> WishlistItems { get; set; }

        public virtual int ItemCount
        {
            get { return WishlistItems.Count; }
        }
    }
}

MrCMS.Web/Apps/Ecommerce/Controllers/WishlistController.cs
using System;
using System.Collections.Generic;
using System.Web.Mvc;
using MrCMS.Web.Apps.Ecommerce.Entities.Products;
using MrCMS.Web.Apps.Ecommerce.Models;
using MrCMS.Web.Apps.Ecommerce.Pages;
using MrCMS.Web.Apps.Ecommerce.Services.Wishlists;
using MrCMS.Web.Apps.Ecommerce.Settings;
using MrCMS.Website;
using MrCMS.Website.Controllers;

namespace MrCMS.Web.Apps.Ecommerce.Controllers
{
    public class WishlistController : MrCMSAppUIController<EcommerceApp>
    {
        private readonly IWishlistUIService _wishlistUIService;
        private readonly CartModel _cartModel;

        public WishlistController(IWishlistUIService wishlistUIService, CartModel cartModel)
        {
            _wishlistUIService = wishlistUIService;
            _cartModel = cartModel;
        }

        public ActionResult Show(ShowWishlist page, string id)
        {
            if (!MrCMSApplication.Get<EcommerceSettings>().EnableWishlists)
                return Redirect("/");

            var wishlist = _wishlistUIService.GetWishlist(id);
            if (wishlist == null)
                return Redirect("~");
            ViewData["wishlist"] = wishlist;
            ViewData["my-wishlist"] = string.IsNullOrWhiteSpace(id);
            ViewData["cart"] = _cartModel;

            return View(page);
        }

        public PartialViewResult Add(ProductVariant productVariant)
        {
            ViewData["in-wishlist"] = _wishlistUIService.IsInWishlist(productVariant);
            ViewData["wisthlist-enabled"] = MrCMSApplication.Get<EcommerceSettings>().EnableWishlists;
            return PartialView(productVariant);
        }


        [HttpPost]
        [ActionName("Add")]
        public JsonResult Add_POST(ProductVariant productVariant)
        {
            _wishlistUIService.Add(productVariant);
            return Json(true);
        }

        [HttpPost]
        [ActionName("Remove")]
        public JsonResult Remove(ProductVariant productVariant)
        {
            _wishlistUIService.Remove(productVariant);
            return Json(true);
        }

        public PartialViewResult Summary()
        {
            return PartialView(_wishlistUIService.GetSummary());
        }

        public PartialViewResult ShowVariant(ProductVariant productVariant)
        {
            ViewData["can-buy-status"] = _wishlistUIService.CanBuy(productVariant);
            return PartialView(productVariant);
        }
    }
}

MrCMS.Web/Apps/Ecommerce/Views/Wishlist/Add.cshtml
@model MrCMS.Web.Apps.Ecommerce.Entities.Products.ProductVariant
@{
    var inWishlist = ViewData["in-wishlist"] is bool && (bool)ViewData["in-wishlist"];
    var enabled = (bool)ViewData["wisthlist-enabled"];
}
@{
    if (enabled)
    {
        <div data-add-to-wishlist="@Model.Id" class="padding-bottom-20">
            @if (!inWishlist)
        {
            using (Html.BeginForm("Add", "Wishlist", new { Model.Id }, FormMethod.Post, new { data_wishlist_action = "add", @class = "margin-bottom-5" }))
            {
                <input type="submit" class="btn btn-default btn-sm" value="@Resource("Add to wishlist")" />
            }
        }
        else
        {
            using (Html.BeginForm("Remove", "Wishlist", new { Model.Id }, FormMethod.Post, new { data_wishlist_action = "remove", @class = "margin-bottom-5" }))
            {
                <input type="submit" class="btn btn-warning btn-sm" value="@Resource("Remove from wishlist")" />
            }
        }
        </div>
    }
}

MrCMS.Web/Apps/Ecommerce/Views/Wishlist/ShowVariant.cshtml
@using System.Drawing
@using MrCMS.Helpers
@using MrCMS.Web.Apps.Ecommerce.Helpers
@using MrCMS.Web.Apps.Ecommerce.Models
@using MrCMS.Web.Apps.Ecommerce.Models.StockAvailability
@using MrCMS.Web.Apps.Ecommerce.Services
@using MrCMS.Web.Apps.Ecommerce.Services.Pricing
@using MrCMS.Web.Apps.Ecommerce.Settings
@using MrCMS.Website
@model MrCMS.Web.Apps.Ecommerce.Entities.Products.ProductVariant
@{
    CanBuyStatus canBuy = ViewData["can-buy-status"] as CanBuyStatus ?? new CannotOrderQuantity(Model, 0);
    var pricingMethod = MrCMSApplication.Get<IProductPricingMethod>();
    var @abstract = Model.Product != null ? Model.Product.ProductAbstract ?? string.Empty : string.Empty;
}
<div class="row" data-wishlist-item="@Model.Id">
    <div class="hidden-xs col-sm-2 col-md-2">
        <a href="@Model.DirectUrl">
            @RenderImage(Model.DisplayImageUrl, new Size { Width = 150, Height = 150 }, null, null, new { @class = "img-responsive" })
        </a>
    </div>
    <div class="col-xs-12 col-sm-7 col-md-8">
        <h3><a href="@Model.DirectUrl">@(!string.IsNullOrWhiteSpace(Model.Name) ? Model.Name : Model.Product.Name)</a></h3>
        <div class="price">
            @pricingMethod.GetPrice(Model).ToCurrencyFormat()
        </div>

        @{
            var displayPreviousPrice = pricingMethod.GetDisplayPreviousPrice(Model);
        }
        @if (displayPreviousPrice != null)
        {
            <div class="margin-bottom-10">
                <span class="previous-price">@(SiteSettings<EcommerceSettings>().PreviousPriceText) <span style="text-decoration: line-through">@displayPreviousPrice.ToCurrencyFormat()</span></span>
            </div>
        }
        <div class="margin-bottom-10">
            @Html.Raw(@abstract.StripHtml().TruncateString(250))
        </div>
    </div>
    <div class="col-xs-12 col-sm-3 col-md-2">
        <div class="text-right">
            @if (canBuy.OK)
            {
                using (Html.BeginForm("Add", "AddToCart", FormMethod.Post))
                {
                    <button class="btn btn-primary btn-block margin-bottom-10">Add to basket</button>
                    @Html.Hidden("ProductVariant.Id", Model.Id)
                    @Html.Hidden("quantity", 1)
                }
            }
            @{ Html.RenderAction("Add", "Wishlist", new { id = Model.Id }); }
        </div>
    </div>
</div>
<hr />

MrCMS.Web/Apps/Ecommerce/Views/Wishlist/Summary.cshtml
@using MrCMS.Helpers
@using MrCMS.Web.Apps.Ecommerce.Pages
@model MrCMS.Web.Apps.Ecommerce.Models.WishlistSummary
<a data-wishlist-summary="true" href="@(UniquePageHelper.GetUrl<ShowWishlist>())">
Wishlist (@Model.Count)
</a>